### 로그인
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "email" : "testemail2@example.com",
  "password" : "testPassword2!"
}

> {%
    client.global.set("accessToken", response.body.accessToken);
    client.global.set("refreshToken", response.body.refreshToken);
%}
